/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liyiyue_util_JNIUtil */

#ifndef _Included_com_liyiyue_util_JNIUtil
#define _Included_com_liyiyue_util_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liyiyue_util_JNIUtil
 * Method:    setGifToClipBoard
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_liyiyue_util_JNIUtil_setGifToClipBoard
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_liyiyue_util_JNIUtil
 * Method:    getKeyState
 * Signature: ([C)I
 */
JNIEXPORT jint JNICALL Java_com_liyiyue_util_JNIUtil_getKeyState
  (JNIEnv *, jclass, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
